#! /bin/sh
#
# Make a (hard) link of this script to have different effects
# Example: This script name "audio-to-mac" will trigger the first case condition
#	make another file by "ln audio-to-mac audio-to-tv" and running that script
#	will trigger the second case condition.
#
# Installtion of the switchaudiosource binary:
#	% brew install switchaudio-osx
#
# 19.oct.23	ykim
# 9.set.24	ykim - If named as "audio-to" then present options to choose from
#

change_to()
{
	VALUE="$1"
	if [ "$(switchaudiosource -c)" = "$VALUE" ]
	then
		echo "Already set to: $VALUE"
	else
		switchaudiosource -s "$VALUE"
	fi
}

case $0 in
*-mac)
	change_to "MacBook Pro Speakers"
	;;
*-tv)
	change_to "TOSHIBA-TV"
	;;
*-now)
	switchaudiosource -c
	;;
*)
	DEVLIST="$(switchaudiosource -a | grep -v "Microphone" | sort -u)"
	echo "Choose one:"
	echo "$DEVLIST" | cat -n
	read -p "? " itemnum
	TODEV="$(echo "$DEVLIST" | awk -v inum=$itemnum 'NR == inum')"
	[ null"$TODEV" = null ] && echo "Bad choice; nothing change." && exit 1
	change_to "$TODEV"
	;;
esac
