#! /bin/bash
#
# Print members of a given group(s)
#
# 15.jan.2016	yoon@tentmakers.com
#

case $1 in
-v)	VERBOSE=yes; shift ;;
*)	VERBOSE=no ;;
esac

case $1 in
?|"")	echo "Usage: $(basename $0) [-v] [dom1|dom2] group-name user-name"; exit 1 ;;
dom1*)	C=1; shift ;;
dom2*)	C=2; shift;;
*)	C= ;;
esac

case $VERBOSE in
yes)
	set -x
	./gam $C info group $1
	;;
*)
	set -x
	./gam $C info group $1 | awk '/(manager|member|owner):|Total/ { print "  "$1, $2; next }'
	;;
esac
